(function(){'use strict';
const plannerReady=()=>window.EthioPlanner&&document.getElementById('tab-planning');
const labels={am:{files:'የዕቅድ ፋይሎች',blank:'ባዶ ቅጽ አውርድ',filled:'የተሞላ ዕቅድ አውርድ',import:'ዕቅድ አስገባ',choose:'የዕቅድ ፋይል ምረጥ',done:'ዕቅዱ ተጫኗል።',bad:'የዕቅድ ፋይሉ ትክክል አይደለም።'},en:{files:'Planning files',blank:'Download blank form',filled:'Download filled plan',import:'Import plan',choose:'Choose a planning file',done:'Plan imported.',bad:'The planning file is invalid.'},om:{files:'Faayiloota karooraa',blank:'Unkaa duwwaa buufadhu',filled:'Karoora guutame buufadhu',import:'Karoora galchi',choose:'Faayila karooraa filadhu',done:'Karoora galchame.',bad:'Faayilaan karooraa sirrii miti.'},ti:{files:'ፋይላት መደብ',blank:'ባዶ ቅጽ ኣውርድ',filled:'ዝተመልአ መደብ ኣውርድ',import:'መደብ ኣእቱ',choose:'ፋይል መደብ ምረጽ',done:'መደብ ተኣትዩ።',bad:'ፋይል መደብ ቅኑዕ ኣይኮነን።'},so:{files:'Faylasha qorshaha',blank:'Soo dejiso foom madhan',filled:'Soo dejiso qorshaha la buuxiyay',import:'Soo geli qorshe',choose:'Dooro fayl qorshe',done:'Qorshaha waa la soo geliyay.',bad:'Faylka qorshuhu sax ma aha.'}};
const lang=()=>localStorage.getItem('lang')||'en';
const L=k=>(labels[lang()]||labels.en)[k]||labels.en[k]||k;
function parseDelimited(text,delimiter){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/);const rows=[];let field='',row=[],quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(quoted){if(c==='"'&&n==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"'){quoted=true;}else if(c===delimiter){row.push(field);field='';}else if(c==='\n'){row.push(field);rows.push(row);row=[];field='';}else if(c==='\r'){}else field+=c;}if(field!==''||row.length){row.push(field);rows.push(row);}return rows;}
function dateValue(s){const m=String(s||'').trim().match(/^(\d+)-(\d{1,2})-(\d{1,2})$/);if(!m)throw new Error('Invalid Ethiopian date');const d={ey:+m[1],em:+m[2],ed:+m[3]};window.ethiopianToJdn(d.ey,d.em,d.ed);return d;}
function importJson(text){const p=JSON.parse(text);if(!p||!Array.isArray(p.rows)||!p.start)return null;p.start=dateValue(window.EthioPlanner.dateLabel(p.start));if(p.endDate)p.endDate=dateValue(window.EthioPlanner.dateLabel(p.endDate));p.rows=p.rows.map(r=>({...r,date:dateValue(window.EthioPlanner.dateLabel(r.date)),status:r.status||'planned',title:r.title||'',details:r.details||''}));return p;}
function importTable(text,delimiter){const rows=parseDelimited(text,delimiter),header=rows.findIndex(r=>r.some(x=>x.trim()==='Ethiopian Date'));if(header<0)throw new Error('Missing Ethiopian Date column');const cols=rows[header].map(x=>x.trim()),idx=n=>cols.indexOf(n),dateI=idx('Ethiopian Date'),titleI=idx('Title'),detailsI=idx('Details'),statusI=idx('Status');const meta=rows[1]||[];const mode=meta[0]||'duration',start=dateValue(meta[1]);const end=meta[2]?dateValue(meta[2]):null;const period=(meta[3]||'1 day').split(/\s+/),interval=(meta[4]||'1 day').split(/\s+/);const p={name:'Imported Ethiopian Plan',periodMode:mode,start,periodValue:+period[0]||1,periodUnit:period[1]||'day',intervalValue:+interval[0]||1,intervalUnit:interval[1]||'day',seasonCategory:'all',seasonId:'all',rows:[]};if(end){p.endDate=end;p.periodUnit='custom';p.endExclusive=window.EthioPlanner.addUnit(end,1,'day');}for(let i=header+1;i<rows.length;i++){const r=rows[i];if(!r[dateI])continue;const d=dateValue(r[dateI]);p.rows.push({id:`${d.ey}-${d.em}-${d.ed}`,date:d,season:{climatic:r[idx('Climatic Season')]||'',fasting:r[idx('Fasting Season')]||'',liturgical:r[idx('Liturgical Season')]||'',greatLentWeek:r[idx('Great Lent Week')]||''},title:titleI>=0?r[titleI]||'':'',details:detailsI>=0?r[detailsI]||'':'',status:statusI>=0&&r[statusI]?r[statusI]:'planned'});}if(!p.rows.length)throw new Error('No planning rows found');return p;}
function importPlan(text,name){let p;if(/\.json$/i.test(name))p=importJson(text);else if(/\.tsv$/i.test(name))p=importTable(text,'\t');else if(/\.csv$/i.test(name))p=importTable(text,',');else{try{p=importJson(text);}catch(_){p=importTable(text,',');}}if(!p)throw new Error('Invalid plan');p.id=`imported-${Date.now()}`;window.__importedPlanningPlan=p;return p;}
function download(plan,format){window.EthioPlanner.downloadPlan(plan,format);}
function addControls(){if(!plannerReady()||document.getElementById('planning-file-tools'))return;const host=document.querySelector('#tab-planning .planning-card');if(!host)return;const box=document.createElement('section');box.id='planning-file-tools';box.className='planning-file-tools';box.setAttribute('aria-labelledby','planning-file-tools-title');box.innerHTML='<h3 id="planning-file-tools-title">'+L('files')+'</h3><div class="planning-actions"><button type="button" id="planning-blank-form">'+L('blank')+'</button><button type="button" id="planning-filled-form">'+L('filled')+'</button><button type="button" id="planning-import-file">'+L('import')+'</button><input id="planning-file-input" type="file" accept=".json,.csv,.tsv,application/json,text/csv,text/tab-separated-values" hidden aria-label="'+L('choose')+'"></div><div id="planning-file-status" role="status" aria-live="polite"></div>';host.appendChild(box);document.getElementById('planning-blank-form').onclick=()=>{const p=window.__planningCurrentPlan||window.__importedPlanningPlan;if(!p){document.getElementById('planning-file-status').textContent=L('bad');return;}const blank=JSON.parse(JSON.stringify(p));blank.rows=blank.rows.map(r=>({...r,title:'',details:'',status:'planned'}));download(blank,'csv');};document.getElementById('planning-filled-form').onclick=()=>{const p=window.__planningCurrentPlan||window.__importedPlanningPlan;if(!p){document.getElementById('planning-file-status').textContent=L('bad');return;}download(p,'json');};document.getElementById('planning-import-file').onclick=()=>document.getElementById('planning-file-input').click();document.getElementById('planning-file-input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=importPlan(await f.text(),f.name);window.EthioPlanner.savePlan(p);window.__planningCurrentPlan=p;document.getElementById('planning-file-status').textContent=L('done');}catch(err){document.getElementById('planning-file-status').textContent=L('bad')+' '+err.message;}e.target.value='';};}
function sync(){if(plannerReady())addControls();setTimeout(sync,500);}
sync();
})();