'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const {loadApp}=require('./helpers');
const app=loadApp();
const code=fs.readFileSync(path.join(__dirname,'planning.js'),'utf8');
const sandbox={...app,window:app};vm.createContext(sandbox);vm.runInContext(code,sandbox,{filename:'planning.js'});const p=sandbox.EthioPlanner;
const date=(ey,em,ed)=>({ey,em,ed});
const sameDate=(actual,expected)=>{assert.equal(actual.ey,expected.ey);assert.equal(actual.em,expected.em);assert.equal(actual.ed,expected.ed);};

test('generates daily entries for a one-week period',()=>{const plan=p.generateSchedule({start:date(2018,1,1),periodValue:1,periodUnit:'week',intervalValue:1,intervalUnit:'day'});assert.equal(plan.rows.length,7);sameDate(plan.rows[0].date,date(2018,1,1));sameDate(plan.rows[6].date,date(2018,1,7));});
test('generates every 7 days',()=>{const plan=p.generateSchedule({start:date(2018,1,1),periodValue:30,periodUnit:'day',intervalValue:7,intervalUnit:'day'});assert.equal(plan.rows.length,5);sameDate(plan.rows[1].date,date(2018,1,8));});
test('generates monthly intervals using Ethiopian month arithmetic',()=>{const plan=p.generateSchedule({start:date(2018,1,30),periodValue:4,periodUnit:'month',intervalValue:1,intervalUnit:'month'});assert.deepEqual(plan.rows.map(r=>[r.date.ey,r.date.em,r.date.ed]),[[2018,1,30],[2018,2,30],[2018,3,30],[2018,4,30]]);});
test('clamps a 30th day correctly when interval crosses Pagume',()=>{const plan=p.generateSchedule({start:date(2018,12,30),periodValue:2,periodUnit:'month',intervalValue:1,intervalUnit:'month'});sameDate(plan.rows[1].date,date(2018,13,5));});
test('supports arbitrary multi-month and multi-year periods',()=>{const plan=p.generateSchedule({start:date(2015,1,1),periodValue:2,periodUnit:'year',intervalValue:6,intervalUnit:'month'});assert.equal(plan.rows.length,4);sameDate(plan.rows[3].date,date(2016,7,1));});
test('rejects non-positive intervals',()=>assert.throws(()=>p.generateSchedule({start:date(2018,1,1),periodValue:1,periodUnit:'month',intervalValue:0,intervalUnit:'day'})));
test('rejects unsupported units',()=>assert.throws(()=>p.generateSchedule({start:date(2018,1,1),periodValue:1,periodUnit:'quarter',intervalValue:1,intervalUnit:'day'})));
test('CSV export contains all schedule rows and season metadata',()=>{const plan=p.generateSchedule({start:date(2018,1,1),periodValue:3,periodUnit:'day',intervalValue:1,intervalUnit:'day'});plan.name='Test';plan.rows[1].title='ሙከራ';const csv=p.exportText(plan,'csv');assert.match(csv,/Ethiopian Date,Climatic Season,Fasting Season,Liturgical Season,Great Lent Week,Title,Details,Status/);assert.match(csv,/2018-01-02,/);assert.match(csv,/ሙከራ/);});
test('JSON export round-trips plan structure and season metadata',()=>{const plan=p.generateSchedule({start:date(2018,1,1),periodValue:1,periodUnit:'week',intervalValue:1,intervalUnit:'day'});const parsed=JSON.parse(p.exportText(plan,'json'));assert.equal(parsed.rows.length,7);assert.equal(parsed.start.ey,2018);assert.ok(parsed.rows[0].season);});
test('season catalog contains climatic, fasting, liturgical and Great Lent families',()=>{const c=p.getSeasonCatalog();assert.equal(c.climatic.length,4);assert.ok(c.fasting.length>=8);assert.ok(c.liturgical.length>=20);assert.equal(c['lent-week'].length,8);});
test('seasonInfoForDate uses the same season engine as the PWA',()=>{const info=p.seasonInfoForDate(date(2018,1,26));assert.ok(info.climatic);assert.ok(info.fasting);assert.ok(info.liturgical);});
test('filters a schedule to the PWA climatic autumn season',()=>{const catalog=p.getSeasonCatalog();const autumn=catalog.climatic.find(x=>x.id==='autumn');const plan=p.generateSchedule({start:date(2018,1,1),periodValue:4,periodUnit:'month',intervalValue:1,intervalUnit:'day',seasonCategory:'climatic',seasonId:'autumn'});assert.equal(plan.rows.length,90);assert.ok(plan.rows.every(r=>r.season.climatic===autumn.label));});
test('filters a schedule to a selected liturgical season',()=>{const catalog=p.getSeasonCatalog();const first=catalog.liturgical[0];const plan=p.generateSchedule({start:date(2018,1,1),periodValue:1,periodUnit:'month',intervalValue:1,intervalUnit:'day',seasonCategory:'liturgical',seasonId:first.id});assert.equal(plan.rows.length,7);assert.ok(plan.rows.every(r=>r.season.liturgical===first.label));});
test('filters a schedule to a named Great Lent week when that week occurs',()=>{const c=p.getSeasonCatalog()['lent-week'];const plan=p.generateSchedule({start:date(2018,1,1),periodValue:1,periodUnit:'year',intervalValue:1,intervalUnit:'day',seasonCategory:'lent-week',seasonId:c[0].id});assert.ok(plan.rows.length>=6&&plan.rows.length<=7);assert.ok(plan.rows.every(r=>r.season.greatLentWeek===c[0].label));});